### ISSUE TITLE
Questions about Codes of Heatmap

### ISSUE THREAD

**Issue by Tina9** [UMCUGenetics/OvCaBiobank#1]
Hi, I am reading your paper "An organoid platform for ovarian cancer captures
intra- and interpatient heterogeneity" and prepare to study the analysis by repeat your method.
However, after I finished calling cnv, I want to know how to do the heatmap (Extended Data Fig.4).
I have cnv but I don't know how to make the input of heatmap. Should I just split the chromosome at a specific pace?  Then I can merge all the samples' data together and give 0 to those segments without cnv. Is it right?

Thanks for your help at first.

**Comment by jaesvi** [comment]
Hi,
When you are with the FREEC CNV calling, you should put all the *.ratio files in one directory and then specify this in the script [cnv/totalCNV_ratios.R](url). You should be careful with filenames only.
Best,
Jose

**Comment by Tina9** [comment]
Thanks for your answer. 

And I am also confused reading your FREEC config. You didn't use control, right? 

Best,
Tina

**Comment by jaesvi** [comment]
Indeed, because using the somatic mode was creating funky ploidy situations for some samples. So we decided to run it individually for each sample. We also for the blood references to check that there was no CNVs there, which was the case.

**Comment by Tina9** [comment]
Thanks for your answer.

I am using R code in cnv/totalCNV_ratios.R. Could you please tell me what's the name of your cnv_ration_files? Because I don't know the output of `cnv_names`.

![image](https://user-images.githubusercontent.com/16876314/60561934-06666e00-9d88-11e9-894e-b463e8f5b7ae.png)

Thanks for your help again.

Best,
Tina

**Comment by Tina9** [comment]
Besides, could you please tell me what's these 2 files for? And if possible, could you please send me these 2 files?

![image](https://user-images.githubusercontent.com/16876314/60562146-dff50280-9d88-11e9-80c1-f3e2e28be0b2.png)

![image](https://user-images.githubusercontent.com/16876314/60562183-16328200-9d89-11e9-8876-68f358ecd382.png)

Thanks for your help again.

**Comment by jaesvi** [comment]
Hi, sorry for the delayed reply. 
For the first question: 
The samples were named for examples T10.bam_ratio.txt and O10.bam_ratio.txt for a tumor-organoid pair. Therefore cnv names would be a vector of names such as 10T, 10O that allows me to sort the samples later.
For the second: Those two files I used to overlap with CNV calls and remove regions were the mapping is difficult and therefore CNV calls pile up in all the samples, making the plot look ugly. These regions are the centromeres and the short arm of acrocentric chromosomes. For your own reference, I took these regions from the karyotype "karyotype.human.hg19.txt" distributed with the CIRCOS program (http://circos.ca/). I just added those files in the cnv directory.

Best,
Jose

**Comment by Tina9** [comment]
Thanks for your help again.

**Comment by Tina9** [comment]
Could you please help me with the question of the output of Control-Freec? I mailed to them without replying for a long time.

There is a file called *_ratio.txt of Control-Freec's output. And what the connection between ratio and copy number in the file? I read their paper and manual, remaining unsolved.

Thanks for your help.
